POST http://localhost:8080/mockit/routes
Content-Type: application/json

{
    "path": "/test",
    "method": "GET",
    "status": 200,
    "type": "application/json",
    "body": "{\"hello\": \"mockit\"}",
    "once": true
}

###
POST http://localhost:8080/mockit/routes
Content-Type: application/json

{
    "path": "/other",
    "method": "POST",
    "status": 201,
    "type": "text/plain; charset=utf-8",
    "body": "Other route has been called",
    "once": false
}

###
GET http://localhost:8080/test?h=1

###
POST http://localhost:8080/other 
Content-type: application/json

{
    "test": "body"
}

###
GET http://localhost:8080/mockit/requests

###
POST http://localhost:8080/mockit/clear